### ISSUE TITLE
Installation of tuya.py

### ISSUE THREAD

**Issue by nathan951** [sean6541/tuya-homeassistant#4]
I'm new to HA, but can normally follow instructions, so I'm guessing I did something wrong or there is an assumed step I missed.

Here's what I did on "hass.io image 0.61.1":
Created a new folder via windows SMB
"\\HASSIO\config\custom_components\switch"
Created a new file within "\switch" named "tuya.py"
Pasted 83 lines of raw code within "tuya.py" and saved

I added following code to the end of my "switches.yaml" 
(note: I switched a couple of letters in local_key for display, and there is leading spaces 2 before -, 4 before name... )

`  - platform: tuya`
 `   name: Counter`
 `   host: 192.168.1.125`
 `   local_key: 41e5e8464e1ee8ab`
 `   device_id: 01200404bcfabc0f4caf`
 `   id:`
 
I did a restart and even a full reboot.

I don't see anything in the log regarding switch and i so not see the new device "switch.counter" within HA. 

Where do I look for logs showing whats wrong and/or do you see anything I messed?

Thanks,
Nathan

**Comment by SDeGonge** [comment]
I have the same problem.  I'm new to this also so I can't rule out myself as being the problem.
Check the "home-assistant.log" file for any tuya.py errors.  I'm getting a syntax error when it loads this file.

**Comment by nathan951** [comment]
Thanks for the reply, 
I dont see anything related to tuya.py in the logs, did you change/add anything in your customize.yaml in regards to "logger:" to see errors?

Thanks

**Comment by SDeGonge** [comment]
no. I just viewed the file. note that I installed samba share to access this file via windows.

**Comment by NickSee** [comment]
can't guarantee this will be any help to either of you (am also new to Tuya and not an expert at yaml) but think I saw one of you quote your configuration.yaml as having the line "id:" which might cause a syntax error possibly - on mine I commented the whole line out like this #id:1 obviously you could delete it, but i tend to comment out so that the entries remind me at a later date that they could/should be included.

**Comment by NickSee** [comment]
if you are struggling to see anything in logs try 

sudo journalctl -fu home-assistant@homeassistant.service

as soon as you can putty in after a reboot.  You should see any misbehaviour there in realtime.  Ctrl C or scroll up later to read in slow time.

**Comment by nathan951** [comment]
Thanks for all your speedy reply's.

I removed ` id:` line and rebooted, I intentionally left it in there and empty as  readme.md said:
 "leave blank if only one switch" which i understood and leaving it there but value blank. 
Maybe readme should say "remove id: if only one switch"?

So on to next issue, is there something else that needs to be installed "pytuya"?

```
2018-01-28 14:33:48 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform tuya
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 189, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/tuya.py", line 30, in setup_platform
    import pytuya
ModuleNotFoundError: No module named 'pytuya'
```

Thanks again!

**Comment by nathan951** [comment]
Ok, So i did a full reboot (not just restart hass.io) and now my error is:

```
2018-01-28 14:48:54 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.counter fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 201, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 308, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/tuya.py", line 78, in update
    self._state = status['dps'][self._switchid]
KeyError: 1
```

**Comment by NickSee** [comment]
I'm not running Hassio so won't be able to help on everything here Nathan but a couple of things you could check - have you installed the pytuya module (I had to do manually on hassbian - with either pip install or apt-get I can't recall which, so have a hunt around for hass.io approach to this) and are you sure you got the right local key for your device (using a rooted android phone etc or other packet sniffer)?

**Comment by nathan951** [comment]
That must be what I'm missing. The README says "It uses a slightly modified version of the pytuya library (https://github.com/clach04/python-tuya) to directly control the switch device." I assumed some of the code was used to create this custom component, being the modified version. If not, where is this "modified version" that needs to be installed? I think this should be added to read me too.

Also I would appreciate  any help and direction on how to install this module on hass.io. I don't think this has a full raspbian build under it.

**Comment by sean6541** [comment]
nathan951 Remove the empty `id:` at the bottom of your config. It should look like:

```
- platform: tuya
    name: Counter
    host: 192.168.1.125
    local_key: 41e5e8464e1ee8ab
    device_id: 01200404bcfabc0f4caf
```

**Comment by sean6541** [comment]
Also, the "It uses a slightly modified version of the pytuya library (https://github.com/clach04/python-tuya)" in the README has been removed. There was a bug in the pytuya library that i temporarily fixed. That bug has been fixed, so no need for the modification.

**Comment by nathan951** [comment]
Thanks Sean,
I originally left  `id:` line in there and empty as readme.md said:
"leave blank if only one switch" which i understood as, leaving id: there, but "value" blank.
Maybe readme should say "remove id: line, if only one switch"?

After removing `id:` I get additional error listed above, but I'm now assuming that is because i do not have a required dependency installed: https://github.com/clach04/python-tuya , correct?

Do you know how one would go about installing pytuya on HASS.IO to get this component working ?

Thanks for your time and contribution to the community!
Nathan

**Comment by sean6541** [comment]
Home Assistant automatically installs the pytuya library. No need to install it.

**Comment by nathan951** [comment]
I do see the deps folder there along with the pytuna, but I'm still getting the following errors.

I know the IP, DeviceID & localkey are correct, what else should i look at? 

```
KeyError: 1
2018-02-02 15:07:45 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.tuya_garage fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 201, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 308, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/tuya.py", line 79, in update
    self._state = status['dps'][self._switchid]
KeyError: 1
```

**Comment by SDeGonge** [comment]
Not hijacking this thread but I wanted to let you know my progress.  I too am having problems getting it working.  I did manage to get started without an error but was still not able to control my device.

My system: Home Assistant (latest version), HASS-IO (latest version), Pi3, tuya.py (latest version)

1. I'm using an iPhone and the Tuya app to set up my devices but I 1st used my wifes android device and eFamilyCloud to get the DeviceID and LocalKey.  I tried wireshark but didn't have any luck.

2. Set up my switch...
- platform: tuya
  name: plug 213
  host: 192.168.200.213
  local_key: fec84f7791488588
  device_id: 01200738ecfabc81f0b3
  id: 1
Note: If I deleted "id: 1" I would end up with a KeyError: 1

3. After getting my key information I started my Tuya app on my iPhone and added my device there. I'm not sure if the local key is dynamic so it may have changed when assigning the device to Tuya.  That would be bad.  I'm assuming that it didn't

4. Added the tuya.py file to /custom_components/switch
Note: Downloading tuya.py as a file did not work.  That method, for some reason, formatted the download as an html document.  I had to create a new file and copy/pasted the tuya.py contents to it.

5. cycled power on the Pi

6. Checked the home-assistant.log and it was clean - no errors :)

7. Actually tried to control my device via Home Assistant. Clicked the switch, Slider moved to on position, Got a message that said "Turned on plug 213", nothing happened and the slider went back to the off position. :(

That's where I'm at.  Could it be that the local key has changed or can it be that my switches just aren't compatible.  Anyway, hope any of the information I provided is helpful.

Also, Here is the error that I get after attempting to turn on my device....

Traceback (most recent call last):
  File "/config/custom_components/switch/tuya.py", line 77, in update
    status = self._device.status()
  File "/config/deps/lib/python3.6/site-packages/pytuya/__init__.py", line 249, in status
    data = self._send_receive(payload)
  File "/config/deps/lib/python3.6/site-packages/pytuya/__init__.py", line 169, in _send_receive
    data = s.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 201, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 308, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/tuya.py", line 83, in update
    raise ConnectionError("Failed to update status.")
ConnectionError: Failed to update status.

**Comment by mattogodoy** [comment]
@SDeGonge the exact same thing is happening to me. I used this to capture the LocalKey:
https://github.com/bobalob/TuyaKeyGrab

After following the configuration steps, the switch shows up un my dashboard, but with the exact same behaviour as yours. 
There is one more thing though: The switch in the dashboard reflects the state of my socket correctly. When I turn it on using the eFamilyCloud app, the switch goes on in HA (with some delay, of course). When I turn it off, it reflects in HA too.

The problem comes when I try to toggle it from HA. Then I get the same behaviour as you and the exact same error in the log.

Did you have any luck making it work?
@sean6541 any ideas about this?

Thanks!

**Comment by SDeGonge** [comment]
> Did you have any luck making it work?
No. I just started from scratch with my Pi.
Still the same issue, not control.  I do get the status but it takes 20 seconds to see the state change if I manually toggle my device via the device itself.
I also took a look at the pytuya code "https://github.com/clach04/python-tuya" and from what I can see, getting the status does not require the local key but controlling it does require it.

**Comment by mattogodoy** [comment]
Well, that's exactly what I found out last night. Let us know if you find out how to make it work! I'll do the same.

**Comment by SDeGonge** [comment]
Will do.

**Comment by maniak666** [comment]
Hi All, I get the error:

`   General Errors: 
    - Platform not found: switch.tuya`

on my config check. I checked that I have the right path by putting another custom component in the right directory. Any hints/ideas? The component apparently is not loading.

Highly appreciate your input!

**Comment by ManuelSchurr** [comment]
Apparently a new localKey is generated/created every time a device is "set up" in some app. It might even be that the localKey for already set up devices changes when a new device is set up, but I'm not absolutely sure about that.
What I have read and experienced is that the devices can apparently only connect to one TCP client at a time, meaning they can either be controlled by HA or some app. That means that I set up all my devices at once, captured my network traffic via my router, analyzed the packages with Wireshark (analyzing packages for String content of "localKey") and then used this information in the switches.yaml file. Afterwards I uninstalled the app and do not plan to use it again. This approach has worked for me. I can sometimes control the switch via the dashboard, that is however not too stable. I can control multiple switches perfectly well and instantly via the "services" tab by calling "switch.turn_off"/"switch.turn_on".

Hope this helps. Essence: localKey changes every time a device is configured in some app

Note: the device_id seems to be constant, the ip must be set static/should naturally not change over time.

**Comment by martinmax** [comment]
@SDeGonge any luck, im having the same issue.

**Comment by martinmax** [comment]
Ok guys so i did it. 

First problem is that this is not gonna work if you have any other app like Smart Home or Tuya App opened on your mobile device since it opens a socket i guess and the device allows only one connection at the time. 

Once I've killed my app I saw that this library was not showing in HA and was throwing an error. 
I've fixed that error by changing line 78 from self._state = status['dps'][self._switchid] to                     self._state = status['dps'][str(self._switchid)]

**Comment by egrinaldi** [comment]
@martinmax Do they work on your setup?

**Comment by martinmax** [comment]
Sure, my setup now is working as expected. I also deleted the Android app from my phone since sometimes was opening a connection with the light switch.

**Comment by njloki30** [comment]
Hey all any help on the error below? I completed the following steps.
Created folders config/custom_components/switch
created new (blank) file tuya.py in the switch folder. 
copied source from Git into the tuya.py file and saved

Added the following into configuration.yaml
switch:
- platform: tuya
  name: "Smart Plug 1"
  #host: http://10.0.0.133
  local_key: ahg3J1WYWKKAWA1L
  device_id: 02200216ecfabc87ea94
  id: '1'

Error log shows 
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 56, in async_setup_component
    return await task
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 116, in _async_setup_component
    conf_util.async_process_component_config(hass, config, domain)
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 645, in async_process_component_config
    platform = get_platform(domain, p_name)
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 104, in get_platform
    return get_component(PLATFORM_FORMAT.format(domain, platform))
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/switch/tuya.py", line 82, in <module>
    raise ConnectionError("Failed to update status.")
ConnectionError: Failed to update status.

**Comment by njloki30** [comment]
Has anyone seen this error before? I"m not sure what I"m missing. 
I have tuya.py installed in /home/homeassistant/.homeassistant/custom_components/switch/ and /config/custom_components/switch (because I'm not sure where it's supposed to go. 
my Config yaml looks like this.
- platform: tuya
    name: SmartPlug1
    host: 10.0.0.133
    device_id: 02XXXXXXXXDEVID
    local_key: a1XXXXXXLOCALKEY
    id: 1

This is the error showing in the dev logs. 

starting version 3.2.4 Testing configuration at /config Fatal error while loading config: Failed to update status. Failed config General Errors: - Failed to update status. Successful config (partial)

1:27 AM components/hassio/__init__.py (ERROR)
starting version 3.2.4
Testing configuration at /config
Fatal error while loading config: Failed to update status.
Failed config
  General Errors: 
    - Failed to update status.
Successful config (partial)
